networks:
  quranku_network:
    name: quranku_network
    driver: bridge

volumes:
  mysql-data:

services:
  mysql:
    image: mysql
    container_name: mysql_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 178292219
      MYSQL_DATABASE: quranku_app
    # ports:
    #   - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - quranku_network

  quranku_app:
    image: reinjin/quranku_app:latest
    container_name: quranku_app
    environment:
      SECRET_KEY: your_secret_key
      JWT_SECRET_KEY: your_JWT_secretkey
      DATABASE_URL: mysql+pymysql://root:178292219@mysql_container:3306/quranku_app
    ports:
      - "5003:5003"
    restart: always
    networks:
      - quranku_network

