"""Create history_belajar table

Revision ID: 70004d2c5004
Revises: bd61c7459229
Create Date: 2024-10-19 03:54:24.541611

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '70004d2c5004'
down_revision = 'bd61c7459229'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('history_belajar',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('huruf', sa.String(length=10), nullable=False),
    sa.Column('tanggal', sa.Date(), nullable=False),
    sa.Column('waktu', sa.Time(), nullable=False),
    sa.Column('kondisi', sa.Enum('fathah', 'kasroh', 'dhommah', name='kondisi_enum'), nullable=False),
    sa.Column('hasil', sa.Enum('kurang', 'benar', name='hasil_enum'), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('history_belajar')
    # ### end Alembic commands ###
